def apply_agathadaimon_method(chart_data):
    result = []
    sun_letter = agathadaimon_dict[
        chart_data["sun"]["sign"], int(chart_data["sun"]["position"])
    ]
    moon_letter = agathadaimon_dict[
        chart_data["moon"]["sign"], int(chart_data["moon"]["position"])
    ]
    asc_letter = agathadaimon_dict[
        chart_data["first_house"]["sign"], int(chart_data["first_house"]["position"])
    ]

    if int(chart_data["hour"]) >= 6 and int(chart_data["hour"]) <= 18:
        suffix = "El"
    else:
        suffix = "Iah"

    result.append(
        "Nome: " + sun_letter + "-" + moon_letter + "-" + asc_letter + "-" + suffix
    )

    result.append(
        "Hebraico: "
        + hebrew_letters[sun_letter]
        + hebrew_letters[moon_letter]
        + hebrew_letters[asc_letter]
        + hebrew_letters[suffix]
    )

    result.append(
        "Descrição: "
        + letter_correspondencies[sun_letter]
        + " "
        + letter_correspondencies[moon_letter]
        + " "
        + letter_correspondencies[asc_letter]
    )

    return result


agathadaimon_dict = {
    ("Ari", 0): "Aleph",
    ("Ari", 1): "Bet",
    ("Ari", 2): "Gimel",
    ("Ari", 3): "Daleth",
    ("Ari", 4): "He",
    ("Ari", 5): "Vav",
    ("Ari", 6): "Zayin",
    ("Ari", 7): "Het",
    ("Ari", 8): "Teth",
    ("Ari", 9): "Yod",
    ("Ari", 10): "Kaph",
    ("Ari", 11): "Lamed",
    ("Ari", 12): "Mem",
    ("Ari", 13): "Nun",
    ("Ari", 14): "Samekh",
    ("Ari", 15): "Ayin",
    ("Ari", 16): "Peh",
    ("Ari", 17): "Tsadi",
    ("Ari", 18): "Qoph",
    ("Ari", 19): "Resh",
    ("Ari", 20): "Shin",
    ("Ari", 21): "Tav",
    ("Ari", 22): "Aleph",
    ("Ari", 23): "Bet",
    ("Ari", 24): "Gimel",
    ("Ari", 25): "Daleth",
    ("Ari", 26): "He",
    ("Ari", 27): "Vav",
    ("Ari", 28): "Zayin",
    ("Ari", 29): "Het",
    ("Tau", 0): "Teth",
    ("Tau", 1): "Yod",
    ("Tau", 2): "Kaph",
    ("Tau", 3): "Lamed",
    ("Tau", 4): "Mem",
    ("Tau", 5): "Nun",
    ("Tau", 6): "Samekh",
    ("Tau", 7): "Ayin",
    ("Tau", 8): "Peh",
    ("Tau", 9): "Tsadi",
    ("Tau", 10): "Qoph",
    ("Tau", 11): "Resh",
    ("Tau", 12): "Shin",
    ("Tau", 13): "Tav",
    ("Tau", 14): "Aleph",
    ("Tau", 15): "Bet",
    ("Tau", 16): "Gimel",
    ("Tau", 17): "Daleth",
    ("Tau", 18): "He",
    ("Tau", 19): "Vav",
    ("Tau", 20): "Zayin",
    ("Tau", 21): "Het",
    ("Tau", 22): "Teth",
    ("Tau", 23): "Yod",
    ("Tau", 24): "Kaph",
    ("Tau", 25): "Lamed",
    ("Tau", 26): "Mem",
    ("Tau", 27): "Nun",
    ("Tau", 28): "Samekh",
    ("Tau", 29): "Ayin",
    ("Gem", 0): "Peh",
    ("Gem", 1): "Tsadi",
    ("Gem", 2): "Qoph",
    ("Gem", 3): "Resh",
    ("Gem", 4): "Shin",
    ("Gem", 5): "Tav",
    ("Gem", 6): "Aleph",
    ("Gem", 7): "Bet",
    ("Gem", 8): "Gimel",
    ("Gem", 9): "Daleth",
    ("Gem", 10): "He",
    ("Gem", 11): "Vav",
    ("Gem", 12): "Zayin",
    ("Gem", 13): "Het",
    ("Gem", 14): "Teth",
    ("Gem", 15): "Yod",
    ("Gem", 16): "Kaph",
    ("Gem", 17): "Lamed",
    ("Gem", 18): "Mem",
    ("Gem", 19): "Nun",
    ("Gem", 20): "Samekh",
    ("Gem", 21): "Ayin",
    ("Gem", 22): "Peh",
    ("Gem", 23): "Tsadi",
    ("Gem", 24): "Qoph",
    ("Gem", 25): "Resh",
    ("Gem", 26): "Shin",
    ("Gem", 27): "Tav",
    ("Gem", 28): "Aleph",
    ("Gem", 29): "Bet",
    ("Can", 0): "Gimel",
    ("Can", 1): "Daleth",
    ("Can", 2): "He",
    ("Can", 3): "Vav",
    ("Can", 4): "Zayin",
    ("Can", 5): "Het",
    ("Can", 6): "Teth",
    ("Can", 7): "Yod",
    ("Can", 8): "Kaph",
    ("Can", 9): "Lamed",
    ("Can", 10): "Mem",
    ("Can", 11): "Nun",
    ("Can", 12): "Samekh",
    ("Can", 13): "Ayin",
    ("Can", 14): "Peh",
    ("Can", 15): "Tsadi",
    ("Can", 16): "Qoph",
    ("Can", 17): "Resh",
    ("Can", 18): "Shin",
    ("Can", 19): "Tav",
    ("Can", 20): "Aleph",
    ("Can", 21): "Bet",
    ("Can", 22): "Gimel",
    ("Can", 23): "Daleth",
    ("Can", 24): "He",
    ("Can", 25): "Vav",
    ("Can", 26): "Zayin",
    ("Can", 27): "Het",
    ("Can", 28): "Teth",
    ("Can", 29): "Yod",
    ("Leo", 0): "Kaph",
    ("Leo", 1): "Lamed",
    ("Leo", 2): "Mem",
    ("Leo", 3): "Nun",
    ("Leo", 4): "Samekh",
    ("Leo", 5): "Ayin",
    ("Leo", 6): "Peh",
    ("Leo", 7): "Tsadi",
    ("Leo", 8): "Qoph",
    ("Leo", 9): "Resh",
    ("Leo", 10): "Shin",
    ("Leo", 11): "Tav",
    ("Leo", 12): "Aleph",
    ("Leo", 13): "Bet",
    ("Leo", 14): "Gimel",
    ("Leo", 15): "Daleth",
    ("Leo", 16): "He",
    ("Leo", 17): "Vav",
    ("Leo", 18): "Zayin",
    ("Leo", 19): "Het",
    ("Leo", 20): "Teth",
    ("Leo", 21): "Yod",
    ("Leo", 22): "Kaph",
    ("Leo", 23): "Lamed",
    ("Leo", 24): "Mem",
    ("Leo", 25): "Nun",
    ("Leo", 26): "Samekh",
    ("Leo", 27): "Ayin",
    ("Leo", 28): "Peh",
    ("Leo", 29): "Tsadi",
    ("Vir", 0): "Qoph",
    ("Vir", 1): "Resh",
    ("Vir", 2): "Shin",
    ("Vir", 3): "Tav",
    ("Vir", 4): "Aleph",
    ("Vir", 5): "Bet",
    ("Vir", 6): "Gimel",
    ("Vir", 7): "Daleth",
    ("Vir", 8): "He",
    ("Vir", 9): "Vav",
    ("Vir", 10): "Zayin",
    ("Vir", 11): "Het",
    ("Vir", 12): "Teth",
    ("Vir", 13): "Yod",
    ("Vir", 14): "Kaph",
    ("Vir", 15): "Lamed",
    ("Vir", 16): "Mem",
    ("Vir", 17): "Nun",
    ("Vir", 18): "Samekh",
    ("Vir", 19): "Ayin",
    ("Vir", 20): "Peh",
    ("Vir", 21): "Tsadi",
    ("Vir", 22): "Qoph",
    ("Vir", 23): "Resh",
    ("Vir", 24): "Shin",
    ("Vir", 25): "Tav",
    ("Vir", 26): "Aleph",
    ("Vir", 27): "Bet",
    ("Vir", 28): "Gimel",
    ("Vir", 29): "Daleth",
    ("Lib", 0): "He",
    ("Lib", 1): "Vav",
    ("Lib", 2): "Zayin",
    ("Lib", 3): "Het",
    ("Lib", 4): "Teth",
    ("Lib", 5): "Yod",
    ("Lib", 6): "Kaph",
    ("Lib", 7): "Lamed",
    ("Lib", 8): "Mem",
    ("Lib", 9): "Nun",
    ("Lib", 10): "Samekh",
    ("Lib", 11): "Ayin",
    ("Lib", 12): "Peh",
    ("Lib", 13): "Tsadi",
    ("Lib", 14): "Qoph",
    ("Lib", 15): "Resh",
    ("Lib", 16): "Shin",
    ("Lib", 17): "Tav",
    ("Lib", 18): "Aleph",
    ("Lib", 19): "Bet",
    ("Lib", 20): "Gimel",
    ("Lib", 21): "Daleth",
    ("Lib", 22): "He",
    ("Lib", 23): "Vav",
    ("Lib", 24): "Zayin",
    ("Lib", 25): "Het",
    ("Lib", 26): "Teth",
    ("Lib", 27): "Yod",
    ("Lib", 28): "Kaph",
    ("Lib", 29): "Lamed",
    ("Sco", 0): "Mem",
    ("Sco", 1): "Nun",
    ("Sco", 2): "Samekh",
    ("Sco", 3): "Ayin",
    ("Sco", 4): "Peh",
    ("Sco", 5): "Tsadi",
    ("Sco", 6): "Qoph",
    ("Sco", 7): "Resh",
    ("Sco", 8): "Shin",
    ("Sco", 9): "Tav",
    ("Sco", 10): "Aleph",
    ("Sco", 11): "Bet",
    ("Sco", 12): "Gimel",
    ("Sco", 13): "Daleth",
    ("Sco", 14): "He",
    ("Sco", 15): "Vav",
    ("Sco", 16): "Zayin",
    ("Sco", 17): "Het",
    ("Sco", 18): "Teth",
    ("Sco", 19): "Yod",
    ("Sco", 20): "Kaph",
    ("Sco", 21): "Lamed",
    ("Sco", 22): "Mem",
    ("Sco", 23): "Nun",
    ("Sco", 24): "Samekh",
    ("Sco", 25): "Ayin",
    ("Sco", 26): "Peh",
    ("Sco", 27): "Tsadi",
    ("Sco", 28): "Qoph",
    ("Sco", 29): "Resh",
    ("Sag", 0): "Shin",
    ("Sag", 1): "Tav",
    ("Sag", 2): "Aleph",
    ("Sag", 3): "Bet",
    ("Sag", 4): "Gimel",
    ("Sag", 5): "Daleth",
    ("Sag", 6): "He",
    ("Sag", 7): "Vav",
    ("Sag", 8): "Zayin",
    ("Sag", 9): "Het",
    ("Sag", 10): "Teth",
    ("Sag", 11): "Yod",
    ("Sag", 12): "Kaph",
    ("Sag", 13): "Lamed",
    ("Sag", 14): "Mem",
    ("Sag", 15): "Nun",
    ("Sag", 16): "Samekh",
    ("Sag", 17): "Ayin",
    ("Sag", 18): "Peh",
    ("Sag", 19): "Tsadi",
    ("Sag", 20): "Qoph",
    ("Sag", 21): "Resh",
    ("Sag", 22): "Shin",
    ("Sag", 23): "Tav",
    ("Sag", 24): "Aleph",
    ("Sag", 25): "Bet",
    ("Sag", 26): "Gimel",
    ("Sag", 27): "Daleth",
    ("Sag", 28): "He",
    ("Sag", 29): "Vav",
    ("Cap", 0): "Zayin",
    ("Cap", 1): "Het",
    ("Cap", 2): "Teth",
    ("Cap", 3): "Yod",
    ("Cap", 4): "Kaph",
    ("Cap", 5): "Lamed",
    ("Cap", 6): "Mem",
    ("Cap", 7): "Nun",
    ("Cap", 8): "Samekh",
    ("Cap", 9): "Ayin",
    ("Cap", 10): "Peh",
    ("Cap", 11): "Tsadi",
    ("Cap", 12): "Qoph",
    ("Cap", 13): "Resh",
    ("Cap", 14): "Shin",
    ("Cap", 15): "Tav",
    ("Cap", 16): "Aleph",
    ("Cap", 17): "Bet",
    ("Cap", 18): "Gimel",
    ("Cap", 19): "Daleth",
    ("Cap", 20): "He",
    ("Cap", 21): "Vav",
    ("Cap", 22): "Zayin",
    ("Cap", 23): "Het",
    ("Cap", 24): "Teth",
    ("Cap", 25): "Yod",
    ("Cap", 26): "Kaph",
    ("Cap", 27): "Lamed",
    ("Cap", 28): "Mem",
    ("Cap", 29): "Nun",
    ("Aqu", 0): "Samekh",
    ("Aqu", 1): "Ayin",
    ("Aqu", 2): "Peh",
    ("Aqu", 3): "Tsadi",
    ("Aqu", 4): "Qoph",
    ("Aqu", 5): "Resh",
    ("Aqu", 6): "Shin",
    ("Aqu", 7): "Tav",
    ("Aqu", 8): "Aleph",
    ("Aqu", 9): "Bet",
    ("Aqu", 10): "Gimel",
    ("Aqu", 11): "Daleth",
    ("Aqu", 12): "He",
    ("Aqu", 13): "Vav",
    ("Aqu", 14): "Zayin",
    ("Aqu", 15): "Het",
    ("Aqu", 16): "Teth",
    ("Aqu", 17): "Yod",
    ("Aqu", 18): "Kaph",
    ("Aqu", 19): "Lamed",
    ("Aqu", 20): "Mem",
    ("Aqu", 21): "Nun",
    ("Aqu", 22): "Samekh",
    ("Aqu", 23): "Ayin",
    ("Aqu", 24): "Peh",
    ("Aqu", 25): "Tsadi",
    ("Aqu", 26): "Qoph",
    ("Aqu", 27): "Resh",
    ("Aqu", 28): "Shin",
    ("Aqu", 29): "Tav",
    ("Pis", 0): "Aleph",
    ("Pis", 1): "Bet",
    ("Pis", 2): "Gimel",
    ("Pis", 3): "Daleth",
    ("Pis", 4): "He",
    ("Pis", 5): "Vav",
    ("Pis", 6): "Zayin",
    ("Pis", 7): "Het",
    ("Pis", 8): "Teth",
    ("Pis", 9): "Yod",
    ("Pis", 10): "Kaph",
    ("Pis", 11): "Lamed",
    ("Pis", 12): "Mem",
    ("Pis", 13): "Nun",
    ("Pis", 14): "Samekh",
    ("Pis", 15): "Ayin",
    ("Pis", 16): "Peh",
    ("Pis", 17): "Tsadi",
    ("Pis", 18): "Qoph",
    ("Pis", 19): "Resh",
    ("Pis", 20): "Shin",
    ("Pis", 21): "Tav",
    ("Pis", 22): "Aleph",
    ("Pis", 23): "Bet",
    ("Pis", 24): "Gimel",
    ("Pis", 25): "Daleth",
    ("Pis", 26): "He",
    ("Pis", 27): "Vav",
    ("Pis", 28): "Zayin",
    ("Pis", 29): "Het",
}

letter_correspondencies = {
    "Aleph": "Andrógina; Porém mais Masculino do que feminina; Espiritual; Geralmente com Asas; do tipo bem mais magro",
    "Bet": " Masculino. Ativa e ligeira e colorida.",
    "Gimel": "Feminina; Grisalha, bela porém mutável. Rosto e corpo bem mais arrendondado.",
    "Daleth": " Feminina. Muito bela e atrativa. Rosto e corpo bem mais arrendondados.",
    "He": "Feminina. Fera, forte, fogosa;",
    "Vav": "Masculino. Forte e estável. Um pouco desajeitada e pesada.",
    "Zayin": "Masculino. Delgado e Inteligente.",
    "Het": "Feminina. Cara arrendondada. Sem muita expressão.",
    "Teth": "Feminina. Tendendo a forte e fogosa.",
    "Yod": "Feminina. Muito branca e um pouco delicada.",
    "Kaph": "Masculino. Grande e forte.",
    "Lamed": "Feminina. Bem proporcional.",
    "Mem": "Andrógina. Porém mais feminina do que masculina. Reflexiva, sonhadora.",
    "Nun": "Masculino. Um rosto quadrado mostrando determinação. Um pouco obscuro.",
    "Samekh": "Masculino. Rosto delgado e expressivo.",
    "Ayin": "Masculino. Um pouco mecânico.",
    "Peh": "Feminina. Fera, forte e dedicada.",
    "Tsadi": "Feminina. Pensativa e intelectual.",
    "Qoph": "Masculino. Face e corpo arredondados.",
    "Resh": "Masculino. Orgulhoso e dominante.",
    "Shin": "Andrógina. Porém mais masculino do que feminino. Fera, ativo. ",
    "Tav": "Andrógina. Porém mais masculino do que feminino. Obscuro e pardo.",
}

hebrew_letters = {
    "Aleph": "א",
    "Bet": "ב",
    "Gimel": "ג",
    "Daleth": "ד",
    "He": "ה",
    "Vav": "ו",
    "Zayin": "ז",
    "Het": "ח",
    "Teth": "ט",
    "Yod": "י",
    "Kaph": "כ",
    "Lamed": "ל",
    "Mem": "מ",
    "Nun": "נ",
    "Samekh": "ס",
    "Ayin": "ע",
    "Peh": "פ",
    "Tsadi": "צ",
    "Qoph": "ק",
    "Resh": "ר",
    "Shin": "ש",
    "Tav": "ת",
    "El": "אֵל",
    "Iah": "יָהּ",
}
